nfrechette/acl

- includes/acl/clip_reader/clip_reader.h
- includes/acl/compression/animation_clip.h
- includes/acl/compression/skeleton.h
- includes/acl/core/memory.h
- includes/acl/core/string.h
- includes/acl/core/string_view.h
- includes/acl/sjson/sjson_parser.h
- tools/acl_compressor/sources/main.cpp
* Reused make_unique's syntax where possible
* Eliminated the need for shared_ptr as well as the functions
supporting it.  Since the skeleton might or might not outlive the
clip, the AnimationClip cannot keep a reference to the skeleton.
* Added StringView C string constructor to mirror the assignment op
* Dropped redundant { } bracing just one statement with no else
> Minor improvements and simplification.

- includes/acl/algorithm/uniformly_sampled/algorithm.h
- includes/acl/algorithm/uniformly_sampled/decoder.h
- includes/acl/core/ialgorithm.h
- tools/acl_compressor/sources/main.cpp
This change also lets the decoder perform one-time initialization and
decide itself, based on the clip, how much memory is required for the
context.  This particular decoder doesn't need a dynamically sized
context, but others (particularly the spline decoder) will.
> Align the decompression context to better use the memory cache.

- tools/fbx2acl/fbx2acl.py
Otherwise it creates a clip of the correct length but with poses read from the stack the animator left selected as the current one.
> Select the animation stack before reading the poses.

- includes/acl/core/memory.h
- tests/CMakeLists.txt
- tests/sources/main.cpp
- tools/acl_compressor/CMakeLists.txt
- tools/acl_compressor/sources/main.cpp
```
===============================================================================
All tests passed (170 assertions in 6 test cases)
```
Consider this a proof of concept, you shouldn't really be using `conio.h` in 2017…
`#include <windows.h>` is also a bit iffy in this case, but I'll let you solve that yourself.
> Port to GCC on Linux

- .travis.yml
- make.py
It seems some tests fail:
```
$ python3 make.py -clean -build -unit_test -${COMPILER} -Debug -x86
<…snip…>
/home/travis/build/janisozaur/acl/tests/sources/core/test_memory_utils.cpp:108: FAILED:
REQUIRE( padding0 == 4 )
with expansion:
0 == 4
```
> GCC8 for travis

- includes/acl/io/clip_reader.h
- includes/acl/io/clip_writer.h
Fix two warning when compiling for UE4 Editor on Mac. I simply renamed the variable that was unhappy with the shadowing.
clip_reader.h:371:48: error: declaration shadows a local variable [-Werror,-Wshadow]
clip_writer.h:50:46: error: declaration shadows a local variable [-Werror,-Wshadow]
> Fix compilation warning on OSX.

- CMakeLists.txt
It is otherwise difficult to develop in the Visual Studio IDE, because the source code is littered with highlighted false positive errors.
> Use the path to the ACL headers in the "acl" project.

- docs/getting_started.md
- includes/acl/algorithm/uniformly_sampled/decoder.h
- includes/acl/algorithm/uniformly_sampled/encoder.h
- includes/acl/compression/animation_clip.h
- includes/acl/compression/stream/clip_context.h
- includes/acl/compression/stream/quantize_streams.h
- includes/acl/compression/stream/segment_streams.h
- includes/acl/compression/stream/write_segment_data.h
- includes/acl/compression/stream/write_stats.h
- includes/acl/core/algorithm_versions.h
- includes/acl/core/compressed_clip.h
- includes/acl/core/interpolation_utils.h
- make.py
- tools/acl_decompressor/acl_decompressor.py
perf(decompression): Optimize the decompression seek function
The old function performed a linear search to find the segments
we need to sample a time T. This can be slow for long clips.
Instead we now make an approximate guess where the first
segment we need lives since the segment sizes are near uniform.
This allows us to only check neighboring segments in O(1).
Includes minor changes and cleanup as well.
Fixes #185
> perf(decompression): optimize the decompression seek function

- includes/acl/decompression/decompress_data.h
Bool flag arrays ended up on the stack with read/writes happening there as well.
On x64, instructions exist to work directly from memory and the asm generated
was short and concise but that wasn't the case on ARM. Instead, we now use a
bit field which nicely fits into a single register. This leads to shorter and faster
assembly.
Fixes #193
On x64 the compiler sometimes struggles with byte/word arithmetic and performs
needless zero extension here and there.
> perf(decompression): convert flag arrays into a bit field

- cmake/Toolchain-Android.cmake
- make.py
- tools/acl_compressor/acl_compressor.py
- tools/acl_decompressor/acl_decompressor.py
- tools/graph_generation/gen_full_error_stats.py
Because we might be adding or removing configs, we need to generate the metadata file everytime.
time.clock() is deprecated in python 3.3, switching to time.perf_counter() instead.
Fix processor count detection to be cross-platform.
Fixes #197
Fixes #196
> fix(setup): various python and android fixes

- includes/acl/compression/stream/quantize_streams.h
- tools/acl_compressor/acl_compressor.py
- tools/acl_compressor/main_generic/CMakeLists.txt
- tools/acl_decompressor/main_generic/CMakeLists.txt
There is no need to re-create and destroy the quantization context for every segment.
Re-using it saves us from allocating and freeing memory for every segment.
Add python and markdown files to solution for easier editing.
Add total elapsed time in seconds.
Fixes #198
> perf(compression): re-use the quantization context

- docs/creating_a_skeleton.md
- includes/acl/compression/skeleton.h
- make.py
- test_data/README.md
- tools/format_reference.acl.sjson
There is no inherent reason to limit the number of root bones to one.
Rigid body simulations might want to leverage this for optimal packing.
Fixes #187
> feat(compression): add support for multiple root bones

- includes/acl/core/bit_manip_utils.h
`decompress_bone(..)` on PC with popcount is 20% faster on average and 5% faster on a Pixel 3.
> perf(core): enable pop-count type instructions on ARM and Xbox One

- tools/fbx2acl/fbx2acl.py
When I bulk exported Paragon animations using the Unreal Editor, it named the files .FBX, which were not accepted by fbx2acl.py.
> fix(tools): allow conversion of .fbx files regardless of case

- includes/acl/compression/impl/track_database.h
- includes/acl/compression/stream/quantize_streams.h
- includes/acl/compression/stream/sample_streams.h
- includes/acl/core/bitset.h
- includes/acl/core/compiler_utils.h
We query the same bit rates over and over as we iterate to optimize. We now cache the result aggressively for the least recently used 4 bit rates for each track rot/trans/scale. This avoids a massive amount of work. Also split the error calculation function into two to avoid branching in the loop and for cleaner code.
Tracks right now are always uniform but support being variable with keys missing. When uniform,
we don't need to interpolate and we can simply sample one key. Specialized the function with a template argument for easier maintenance and performance.
Fixes #200
> feat(compression): add a track database to cache bit rate queries

- includes/acl/math/quat_32.h
- includes/acl/math/scalar_32.h
- sonar-project.properties
See [here](https://github.com/nfrechette/rtm/issues/29) for details.
Also fix VS2019 code gen bug and sonar cloud.
> feat(quat): optimize quat_mul for SSE2 by using XOR to flip the sign bit

- includes/acl/core/bit_manip_utils.h
- includes/acl/core/bitset.h
- tests/sources/core/test_bit_manip_utils.cpp
This enables support on Windows ARM and cleans up the code.
Fixes #215
> fix(core): fix bit counting to use NEON intrinsic instead of GCC builtin

- includes/acl/algorithm/uniformly_sampled/decoder.h
- includes/acl/compression/impl/write_decompression_stats.h
- includes/acl/decompression/decompress.h
It can lead to warnings with GCC and it isn't consistent with anything else within ACL.
> refactor: remove release() pattern from the decompression context

- README.md
- appveyor.yml
- includes/acl/core/bit_manip_utils.h
- includes/acl/core/impl/compiler_utils.h
- make.py
- tools/appveyor_ci.bat
Split appveyor into a batch file for easier local testing.
> chore: add support for clang with VS2019

- includes/acl/core/ansi_allocator.h
aligned_alloc(..) doesn't work with emscripten, use posix_memalign(..) instead.
> fix(core): properly handle aligned allocations with emscripten for ANSI allocator

- includes/acl/algorithm/uniformly_sampled/decoder.h
- includes/acl/compression/impl/compact_constant_streams.h
- includes/acl/compression/impl/convert_rotation_streams.h
- includes/acl/compression/impl/normalize_streams.h
- includes/acl/compression/impl/quantize_streams.h
- includes/acl/compression/impl/track_stream.h
- includes/acl/core/iallocator.h
The printf format specified for size_t is %zu.
The printf format specifier for uint8 is supposed to be %hhu but that wasn't very portable.
Compiling on Windows 32/64 Visual C++, Linux GCC, iOS, MacOS and various Android flavors to silence warnings and analyze errors.
> fix: ensure proper format specifiers are used for size_t and uint8_t

- includes/acl/compression/track.h
When calling get_ref() on a track, I noticed that the range_values weren't correct and tracked it down to m_sample_size being 0.  Seemed like it was just missing from these two locations.
acl/tests/sources/io/test_reader_writer.cpp
Would demonstrate this bug, if you look at the error between the compressed and uncompressed data.
> fix(compression): add missing sample_size copy

- includes/acl/decompression/decompress.h
When decompressing tracks, I found that the range_values were often scrambled.
I believe this is the proper fix, only increment the range_values pointer when it's not constant and not a raw_bit_rate
> fix(decompression): only update range_values offsets when necessary

- includes/acl/compression/track.h
Simply a missing const, make_copy won't compile otherwise.
> fix(compression): add missing const to track_typed::make_copy

- includes/acl/algorithm/uniformly_sampled/encoder.h
This ends up pulling in code we don't always need with emscripten/WASM.
> fix(compression): strip out compression timing when not required

- CHANGELOG.md
- docs/creating_a_raw_track_list.md
- includes/acl/compression/impl/constant_track_impl.h
- includes/acl/core/track_types.h
- includes/acl/io/clip_reader.h
- includes/acl/io/clip_writer.h
- tests/sources/io/test_reader_writer.cpp
- tools/format_reference.acl.sjson
Whether a track is constant or not is an implementation detail. It does not need
to be controlled by the user. We can determine whether it should be constant
or not entirely from the precision value desired.
> fix(compression): remove support for constant_threshold from scalar track compression

- includes/acl/compression/compress.h
> fix(compression): avoid crashing when compressing an empty track_array

- .github/workflows/main.yml
- CMakeLists.txt
- appveyor.yml
- cmake/CMakePlatforms.cmake
- external/README.md
- includes/acl/compression/impl/normalize_streams.h
When we check for constant tracks, we use the full vector4 which is fine
for rotations but it could contain garbage for translation/scale.
> fix(compression): zero out W component of translation/scale track ranges

- includes/acl/compression/impl/clip_context.h
- includes/acl/compression/impl/compact_constant_streams.h
- includes/acl/compression/impl/compress.transform.impl.h
- includes/acl/compression/impl/convert.impl.h
- includes/acl/compression/impl/sample_streams.h
- includes/acl/compression/impl/segment_streams.h
- includes/acl/compression/impl/track_bit_rate_database.h
- includes/acl/compression/impl/track_error.impl.h
- includes/acl/compression/impl/track_stream.h
- includes/acl/compression/impl/write_track_metadata.h
- includes/acl/core/additive_utils.h
- includes/acl/core/impl/compiler_utils.h
- includes/acl/core/impl/compressed_headers.h
- includes/acl/core/impl/compressed_tracks.impl.h
- includes/acl/core/impl/debug_track_writer.h
- includes/acl/core/track_desc.h
- includes/acl/core/track_writer.h
- includes/acl/decompression/impl/transform_track_decompression.h
- includes/acl/io/clip_reader.h
- make.py
- tools/acl_compressor/sources/validate_tracks.cpp
- tools/acl_decompressor/sources/benchmark.cpp
ACL_BIND_POSE allows users to change the definition of "default transform" from "identity transform" to "bind transform".
Punting on ACL_BIND_POSE_BINARY, because it would require a version change.  In the meantime, binary ACL metadata applies identity transforms, which works fine for pre-existing files, but will break regression tests for new files that prefer bind transforms.
> feat: improved bind pose handling

- includes/acl/compression/impl/clip_context.h
- includes/acl/compression/impl/compact_constant_streams.h
- includes/acl/compression/impl/normalize_streams.h
- includes/acl/compression/impl/track_stream.h
- includes/acl/core/impl/compiler_utils.h
I noticed constant and default precision issues while working on _fix/improve-quantization-error_, and the fixes were in the vicinity of my ACL_BIND_POSE changes, so I put them in this branch.  Feel free to link this pull request to https://github.com/nfrechette/acl/issues/359
In addition to quality, it buys me a modest 0.2% size improvement over the previous ACL_BIND_POSE(which is a much bigger size improvement over standard ACL).  YMMV.
> fix: improved precision of constant and default tracks

- includes/acl/compression/impl/normalize_streams.h
- includes/acl/compression/impl/quantize_streams.h
Similar to my previous pull request, for constant tracks within segments this time.
> fix: improved precision of constant tracks within segments

- includes/acl/compression/impl/normalize_streams.h
- includes/acl/compression/impl/quantize_track_impl.h
- includes/acl/core/impl/compiler_utils.h
- includes/acl/math/quat_packing.h
- includes/acl/math/scalar_packing.h
- includes/acl/math/vector4_packing.h
- make.py
- tests/sources/math/test_quat_packing.cpp
- tests/sources/math/test_scalar_packing.cpp
- tests/sources/math/test_vector4_packing.cpp
This one is much simpler, and more successful.  Precision improves, and also saves a modest 0.6% of memory in my use case.  Win-win.  Feel free to link this to https://github.com/nfrechette/acl/issues/351.
> fix: improved quantization range

- includes/acl/io/clip_writer.h
This is one of the changes I needed to make to create the acl.sjson file referred to in https://github.com/nfrechette/acl/issues/353#issuecomment-856952432
It only manifests as a single commit in the pull request preview, so I presume that this is clean enough.  LMK otherwise.
> fix: added bind transform support to clip_writer

- includes/acl/compression/impl/sample_streams.h
This should have been included with https://github.com/nfrechette/acl/pull/367, but I missed the sampling part.  :-|
> fix: improved precision of constant track sampling within segments

- includes/acl/compression/impl/normalize_streams.h
- includes/acl/compression/impl/sample_streams.h
This problem was revealed by using ACL_COMPRESSION_OPTIMIZED and ACL_BIND_POSE at the same time.
Stripped dead code from sample_streams as a bonus.
> fix: precision improvement for range weighted averages

- includes/acl/core/string.h
- tools/acl_compressor/sources/acl_compressor.cpp
@nfrechette, minor fix, but with frequent use empty() function, it makes sense.
> refactor: avoid using strlen to test for empty strings

- includes/acl/compression/impl/compact_constant_streams.h
- includes/acl/compression/impl/compress.transform.impl.h
- includes/acl/compression/impl/optimize_looping.h
Additive local space clips can have zero scale which means error is zero if we don't apply the base clip.
> fix(compression): apply base clip when measuring error

- includes/acl/compression/impl/quantize_streams.h
- includes/acl/compression/impl/track_error.impl.h
- includes/acl/compression/transform_error_metrics.h
This is about four months later than I had hoped, but better late than never!
This adds extra context to custom error metrics that wish to compensate for external factors such as animated world space lattice deforms or in my case, already compressed scale factors.
I wasn't sure if two bools or an enum were better for describing is_lossy and is_base. I ended up with the approach I did in case there would ever be a lossy base in the future where both the base and all overrides were compressed in one go. But if there's a desire to change that to an enum, I would have no problem changing it.
Thanks for all the work you do! Hyped for 2.1 after the latest blog post!
> feat(compression): add context to error metric conversion args

- includes/acl/compression/impl/write_stream_data.h
Hi ! First thanks a lot for your library 😃 
I stumbled upon a consistency issue when re-compressing an animation:
In the `group_flush_action()` lambda, the `group_size` var is overridden by 4 in the case of a rotation. In most cases that's fine because we'll memset the next group to 0. But if we have a single rotation group with less than 4 entries, then we rely on the uninitialized values from the stack.
> fix: uninitialized value in write_format_per_track_data
