nfrechette/acl

tools/graph_generation/grapher.r
* still need to handle the unity graphs
=> added R script to generate graphs

.travis.yml, CMakeLists.txt, appveyor.yml, includes/acl/compression/stream/quantize_streams.h, includes/acl/core/memory.h, tests/CMakeLists.txt, tools/acl_compressor/CMakeLists.txt
Please enable Travis-CI: https://travis-ci.org/ this one is free-for-open-source CI service which allows running Linux and macOS jobs.
Currently the code for macOS is broken, so there is no configuration enabled.
=> Add Travis support

tools/fbx2acl/fbx2acl.py
This allows a small section of a larger clip to be extracted for faster testing or analysis.
=> Added window flags to fbx2acl.py

includes/acl/core/ansi_allocator.h
Many aligned allocators impose restrictions on what the alignment can be
and how it relates to allocated size.
Improve the interface to enforce the alignment and size requirements
See
http://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_memalign.html
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-malloc
for reference
=> Improve aligned allocations

includes/acl/compression/stream/quantize_streams.h, includes/acl/compression/stream/sample_streams.h, includes/acl/compression/stream/write_stats.h, tools/acl_compressor/acl_compressor.py
Fix issue with infinite clip duration in stat reporting.
Fixes #199
=> feat(compression): avoid hierarchical sampling when only a single bone is required

includes/acl/compression/stream/sample_streams.h, includes/acl/math/vector4_32.h, includes/acl/math/vector4_64.h, includes/acl/math/vector4_packing.h, tests/sources/math/test_vector4_impl.h, tests/sources/math/test_vector4_packing.cpp
=> feat(math): implement decay functions to avoid packing/unpacking from the stack

CHANGELOG.md, README.md, appveyor.yml, docs/decompressing_a_clip.md, includes/acl/algorithm/uniformly_sampled/decoder.h, includes/acl/algorithm/uniformly_sampled/encoder.h, includes/acl/compression/compress.h, includes/acl/compression/stream/write_segment_data.h, includes/acl/core/bit_manip_utils.h, includes/acl/core/floating_point_exceptions.h, includes/acl/decompression/decompress.h, includes/acl/io/clip_reader.h, sonar-project.properties, tools/acl_compressor/sources/acl_compressor.cpp
=> chore: integrate 1.2.1 changes

.travis.yml, README.md, docs/getting_started.md, make.py, tools/acl_compressor/sources/acl_compressor.cpp
Also fix floating point exceptions when measuring stats/error.
=> chore: various travis/python related changes for OS X

includes/acl/compression/animation_clip.h, includes/acl/compression/compression_settings.h, includes/acl/compression/impl/track_bit_rate_database.h, includes/acl/compression/stream/convert_rotation_streams.h, includes/acl/compression/stream/normalize_streams.h, includes/acl/compression/stream/quantize_streams.h, includes/acl/compression/stream/sample_streams.h, includes/acl/compression/stream/segment_streams.h, includes/acl/compression/stream/track_stream.h, includes/acl/compression/stream/write_range_data.h, includes/acl/compression/stream/write_stream_data.h, includes/acl/core/memory_utils.h, includes/acl/math/vector4_32.h, includes/acl/math/vector4_64.h, includes/acl/math/vector4_packing.h
The SOA branch did a bit of cleanup which is now being merged into mainline.
Other fixes and improvements have also been made.
=> chore: various commits from the SOA branch and others

tests/main_android/AndroidManifest.xml, tests/main_android/CMakeLists.txt, tests/main_android/java/com/acl/unit_tests/MainActivity.java, tests/main_android/jni/main.cpp, tools/acl_compressor/main_android/AndroidManifest.xml, tools/acl_compressor/main_android/CMakeLists.txt, tools/acl_compressor/main_android/java/com/acl/compressor/MainActivity.java, tools/acl_compressor/main_android/jni/main.cpp, tools/acl_decompressor/main_android/CMakeLists.txt, tools/acl_decompressor/main_android/java/com/acl/decompressor/MainActivity.java, tools/acl_decompressor/main_android/jni/main.cpp, tools/regression_tester_android/CMakeLists.txt, tools/regression_tester_android/java/com/acl/regression_tests/MainActivity.java, tools/regression_tester_android/jni/main.cpp
=> fix(android): fix package name on android to be unique

.travis.yml, README.md, make.py, tests/sources/math/test_scalar_packing.cpp, tools/release_scripts/test_everything.py
Fix unit test to use near equal instead of ==.
=> chore: add support for clang 8 and clang 9

external/README.md
=> chore: update Catch2 to v2.11.0

includes/acl/compression/track_error.h, includes/acl/compression/utils.h
Same as legacy error measurement.
=> fix(compression): early exit when no data is present and handle zero error properly

includes/acl/compression/track_array.h, includes/acl/decompression/decompress.h
=> chore: update RTM to latest

includes/acl/compression/animation_track.h, includes/acl/compression/compression_settings.h, includes/acl/compression/impl/compact_constant_streams.h, includes/acl/compression/impl/normalize_streams.h, includes/acl/compression/impl/normalize_track_impl.h, includes/acl/compression/impl/quantize_streams.h, includes/acl/compression/impl/quantize_track_impl.h, includes/acl/compression/skeleton.h, includes/acl/core/impl/debug_track_writer.h, includes/acl/core/track_writer.h, includes/acl/io/clip_reader.h, includes/acl/io/clip_writer.h, includes/acl/math/scalar_packing.h, includes/acl/math/vector4_packing.h, tests/sources/io/test_reader_writer.cpp, tests/sources/math/test_quat_packing.cpp, tools/acl_compressor/sources/acl_compressor.cpp
Added some code to profile RTM.
=> chore: update RTM to 2.0

external/README.md
As pointed out by @Qix- in #379, thanks!
=> docs: fix typo

docs/handling_asserts.md
The contribution of a life time
=> docs: fix minor typo in handling_asserts.md

.github/workflows/benchmark.yml, external/README.md
Will test compilation of the benchmark projects as well as allow us to run it in CI later on.
=> chore(ci): add benchmark workflow

.github/workflows/build_push.yml, .gitignore, CMakeLists.txt, make.py, tools/acl_compressor/sources/validate_tracks.cpp
Fixes #357 
Hooking up to git commit workflow only for now as it adds quite a bit of overhead and we test a wide variety of things regardless. Down the road, a new workflow will be added to test everything to be ran manually when preparing releases.
=> feat: download test data and run regression tests with CI

make.py
=> fix(tools): sort decompression clips by name

.github/workflows/benchmark.yml, .github/workflows/build_pull_request.yml, .github/workflows/build_push.yml, .github/workflows/msvc-analysis.yml, .github/workflows/sonarcloud.yml
Should fix job warnings and msvc analysis failure
=> chore(ci): update github action versions to latest

includes/acl/math/quatf.h
Will lead to leaner and faster assembly on NEON.
=> feat(decompression): use muladd where possible
